<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rte_test" nsURI="http://nces.is.nagoya-u.ac.jp/a-rte/rte-test"
    nsPrefix="rte_test">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="module" value="rte.ecore#//module"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RteTestModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="osStubHeader" lowerBound="1"
        eType="#//OsStubHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comStubHeader" lowerBound="1"
        eType="#//ComStubHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iocMockHeader" lowerBound="1"
        eType="#//IocMockHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swcMockHeader" upperBound="-1"
        eType="#//SwcMockHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="swcMockSource" upperBound="-1"
        eType="#//SwcMockSource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iocMockSource" lowerBound="1"
        eType="#//IocMockSource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bswmMockHeader" upperBound="-1"
        eType="#//BswmMockHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bswmMockSource" upperBound="-1"
        eType="#//BswmMockSource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OsStubHeader" eSuperTypes="rte.ecore#//module/HeaderFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/Constant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComStubHeader" eSuperTypes="rte.ecore#//module/HeaderFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/Constant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IocMockHeader" eSuperTypes="rte.ecore#//module/HeaderFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iocApi" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/IocApi"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwcMockHeader" eSuperTypes="rte.ecore#//module/HeaderFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swcName" lowerBound="1"
        eType="ecore:EDataType rte.ecore#//module/CIdentifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executableEntity" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/ExecutableEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RteTestRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rteTestModule" lowerBound="1"
        eType="#//RteTestModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rteTest" lowerBound="1"
        eType="#//RteTest" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IocMockSource" eSuperTypes="rte.ecore#//module/SourceFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iocApi" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/IocApi"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwcMockSource" eSuperTypes="rte.ecore#//module/SourceFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="swcName" lowerBound="1"
        eType="ecore:EDataType rte.ecore#//module/CIdentifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executableEntity" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/ExecutableEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RteTest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="osStubConstant" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/Constant" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comStubConstant" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/Constant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BswmMockHeader" eSuperTypes="rte.ecore#//module/HeaderFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executableEntity" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/ExecutableEntity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bswmName" lowerBound="1"
        eType="ecore:EDataType rte.ecore#//module/CIdentifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BswmMockSource" eSuperTypes="rte.ecore#//module/SourceFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executableEntity" upperBound="-1"
        eType="ecore:EClass rte.ecore#//module/ExecutableEntity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bswmName" lowerBound="1"
        eType="ecore:EDataType rte.ecore#//module/CIdentifier"/>
  </eClassifiers>
</ecore:EPackage>
