/*
 * File: Rte_Partition_Core1BswPartition.h
 *
 * Generated by A-RTEGEN.
 *
 * Generator version : 1.2.0
 */

#ifndef RTE_PARTITION_Core1BswPartition_H
#define RTE_PARTITION_Core1BswPartition_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "Os.h"
#include "Rte_Common.h"

/*
 * Internal Constant Definitions
 */

/*
 * Internal Global Variable Declarations
 */

/*
 * Internal Function Macro Definitions
 */

/*
 * Proxy Function Table Declarations
 */

/*
 * RTE Lifecycle API Implementation Function Declarations
 */

/*
 *  Basic Software Scheduler Lifecycle API Implementation Function Declarations
 */

/*
 * TrustedFunction Declarations
 */

/*
 * BSW SchedulableEntity Declarations
 */

/*
 * Dependent ExecutableEntity Declarations
 */
#define Rte_Switch_START_SEC_CODE

extern Std_ReturnType Rte_Switch_mode0_currentMode(Rte_ModeType_WdgM_Mode mode);
extern Std_ReturnType Rte_Switch_mode1_currentMode(Rte_ModeType_WdgM_Mode mode);
extern Std_ReturnType Rte_Switch_globalMode_currentMode(Rte_ModeType_WdgM_Mode mode);

#define Rte_Switch_STOP_SEC_CODE

#define WdgM_START_SEC_CODE
#include "WdgM_MemMap.h" /* MISRA RULE 19.1 VIOLATION : It won't be fixed because of Specification of AUTOSAR Memory Mapping */

extern Std_ReturnType	WdgM_CheckpointReached(WdgM_SupervisedEntityIdType port_arg_val_0, WdgM_CheckpointIdType arg1);

#define WdgM_STOP_SEC_CODE
#include "WdgM_MemMap.h" /* MISRA RULE 19.1 VIOLATION : It won't be fixed because of Specification of AUTOSAR Memory Mapping */

/*
 * RTE API Implementation Function Declarations
 */

#define RTE_START_SEC_CODE_Core1BswPartition
#include "MemMap.h" /* MISRA RULE 19.1 VIOLATION : It won't be fixed because of Specification of AUTOSAR Memory Mapping */

#define RTE_STOP_SEC_CODE_Core1BswPartition
#include "MemMap.h" /* MISRA RULE 19.1 VIOLATION : It won't be fixed because of Specification of AUTOSAR Memory Mapping */

/*
 * Signal API Implementation Function Declarations
 */

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* !RTE_PARTITION_Core1BswPartition_H */
