/*
 * File: Rte_WdgState_Type.h
 *
 * Generated by A-RTEGEN.
 *
 * Generator version : 1.2.1
 */

#ifndef RTE_WdgState_Type_H
#define RTE_WdgState_Type_H

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "Rte_Type.h"

/*
 * RTE API Constant Definitions
 */
#define RTE_WDGM_GLOBAL_STATUS_OK				0x00U
#define RTE_WDGM_GLOBAL_STATUS_FAILED			0x01U
#define RTE_WDGM_GLOBAL_STATUS_EXPIRED			0x02U
#define RTE_WDGM_GLOBAL_STATUS_STOPPED			0x03U
#define RTE_WDGM_GLOBAL_STATUS_DEACTIVATED		0x04U

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* !RTE_WdgState_Type_H */
