/*
 * File: Rte_WdgState.h
 *
 * Generated by A-RTEGEN.
 *
 * Generator version : 1.2.1
 */

#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "Rte_WdgState_Type.h"

/*
 * RTE API Constant Definitions
 */

/*
 * RTE API Implementation Function Declarations
 */

extern Std_ReturnType	Rte_Call_SensorButton_LedStateOut_SetLedStateWdgOK();
extern Std_ReturnType	Rte_Call_SensorButton_LedStateOut_SetLedStateWdgFAILED();
extern Std_ReturnType	Rte_Call_SensorButton_LedStateOut_SetLedStateWdgEXPIRED();
extern Std_ReturnType	Rte_Call_SensorButton_LedStateOut_SetLedStateWdgSTOPPED();
extern Std_ReturnType	Rte_Call_SensorButton_LedStateOut_SetLedStateWdgCLEAR();

/*
 * RTE API Definitions
 */

#define Rte_Call_LedStateOut_SetLedStateWdgOK Rte_Call_SensorButton_LedStateOut_SetLedStateWdgOK
#define Rte_Call_LedStateOut_SetLedStateWdgFAILED Rte_Call_SensorButton_LedStateOut_SetLedStateWdgFAILED
#define Rte_Call_LedStateOut_SetLedStateWdgEXPIRED Rte_Call_SensorButton_LedStateOut_SetLedStateWdgEXPIRED
#define Rte_Call_LedStateOut_SetLedStateWdgSTOPPED Rte_Call_SensorButton_LedStateOut_SetLedStateWdgSTOPPED
#define Rte_Call_LedStateOut_SetLedStateWdgCLEAR Rte_Call_SensorButton_LedStateOut_SetLedStateWdgCLEAR

/*
 * RunnableEntity Declarations
 */
#define CddStateLed_START_SEC_CODE
#include "CddStateLed_MemMap.h" /* MISRA RULE 19.1 VIOLATION : It won't be fixed because of Specification of AUTOSAR Memory Mapping */

extern void	WdgState(LedState state);

#define CddLockLed_STOP_SEC_CODE
#include "CddStateLed_MemMap.h" /* MISRA RULE 19.1 VIOLATION : It won't be fixed because of Specification of AUTOSAR Memory Mapping */

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */
